[project]
name = "simple-python-pyinstaller-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dancingmeow", email = "Dancingmeow@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
simple-python-pyinstaller-app = "simple_python_pyinstaller_app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
